In [11]:
import pandas as pd

In [12]:
covid = pd.read_csv("us_counties_covid19_daily.csv")
cases = pd.read_csv("datacommons_data.csv")
deaths = pd.read_csv("datacommons_deaths.csv")

In [13]:
covid = covid.drop(labels=["fips"], axis=1)
covid["date"] = pd.to_datetime(covid["date"])
lastDate = covid["date"].max()
lastReport2020 = covid.loc[covid['date'] >= lastDate]
lastReport2020 = lastReport2020.groupby("state").sum()
lastReport2020

                            cases   deaths
state
Alabama                    267589   3877.0
Alaska                      36083    136.0
Arizona                    361186   6940.0
Arkansas                   169382   2620.0
California                1343145  19876.0
Colorado                   258124   3415.0
Connecticut                127715   5146.0
Delaware                    39096    782.0
District of Columbia        22872    695.0
Florida                   1049630  19083.0
Georgia                    481126   9506.0
Guam                         7946    114.0
Hawaii                      18484    259.0
Idaho                      109764   1037.0
Illinois                   781441  14028.0
Indiana                    377790   6207.0
Iowa                       243385   2682.0
Kansas                     171626   1786.0
Kentucky                   202135   2241.0
Louisiana                  247177   6548.0
Maine                       13127    227.0
Maryland                   212545   4820.0
Massachusetts              252017  10953.0
Michigan                   425776  10313.0
Minnesota                  345340   3979.0
Mississippi                163458   3949.0
Missouri                   334637   4412.0
Montana                     67092    734.0
Nebraska                   138568   1202.0
Nevada                     166187   2309.0
New Hampshire               24138    559.0
New Jersey                 363822  17306.0
New Mexico                 106856   1738.0
New York                   700902  34488.0
North Carolina             388760   5547.0
North Dakota                82510   1013.0
Northern Mariana Islands      106      2.0
Ohio                       467432   6947.0
Oklahoma                   213245   1874.0
Oregon                      83243   1027.0
Pennsylvania               416073  11331.0
Puerto Rico                 89147   1184.0
Rhode Island                62137   1413.0
South Carolina             229235   4517.0
South Dakota                85304   1091.0
Tennessee                  388815   4851.0
Texas                     1333809  23111.0
Utah                       212877    939.0
Vermont                      4894     79.0
Virgin Islands               1613     23.0
Virginia                   251173   4197.0
Washington                 184079   3065.0
West Virginia               53572    829.0
Wisconsin                  437918   3938.0
Wyoming                     35941    257.0

In [14]:
cases = cases.drop(labels=["placeDcid"], axis=1)
cases = cases.rename(columns={"placeName":"state", "CumulativeCount_MedicalConditionIncident_COVID_19_ConfirmedOrProbableCase":"positiveCases"})
deaths = deaths.drop(labels=["placeDcid"], axis=1)
deaths = deaths.rename(columns={"placeName":"state", "CumulativeCount_MedicalConditionIncident_COVID_19_PatientDeceased":"deaths"})
casesAll = cases.join(deaths.set_index("state"), on="state")
casesAll

                   state  positiveCases  deaths
0                Alabama        1300733   19567
1                 Alaska         251388    1212
2                Arizona        2021524   29951
3               Arkansas         835916   11392
4             California        9237134   90422
5               Colorado        1390127   12366
6            Connecticut         758281   10850
7               Delaware         262461    2907
8   District of Columbia         141943    1340
9                Florida        5925668   73948
10               Georgia        2445476   36349
11                Hawaii         241955    1415
12                 Idaho         446138    4930
13              Illinois        3144347   37898
14               Indiana        1702292   23587
15                  Iowa         763782    9529
16                Kansas         776663    8635
17              Kentucky        1337141   15418
18             Louisiana        1238011   17248
19                 Maine         245080    2286
20              Maryland        1031797   14456
21         Massachusetts        1757103   20263
22              Michigan        2425946   36002
23             Minnesota        1452817   12778
24           Mississippi         797575   12444
25              Missouri        1433608   20199
26               Montana         274221    3363
27              Nebraska         479989    4197
28                Nevada         719451   10774
29         New Hampshire         309982    2480
30            New Jersey        2263991   33434
31            New Mexico         522329    7501
32              New York        5154714   67694
33        North Carolina        2661333   23415
34          North Dakota         241127    2315
35                  Ohio        2697058   38428
36              Oklahoma        1040982   14271
37                Oregon         721311    7502
38          Pennsylvania        2821667   44678
39          Rhode Island         371629    3540
40        South Carolina        1474272   17767
41          South Dakota         237812    2912
42             Tennessee        1981990   25895
43                 Texas        6754068   88305
44                  Utah         932480    4747
45               Vermont         123842     637
46              Virginia        1701458   20236
47            Washington        1498708   12747
48         West Virginia         501204    6856
49             Wisconsin        1610673   14413
50               Wyoming         156550    1812
51           Puerto Rico         576096    4210

Generate csv output

In [15]:
casesAll.to_csv("covid.csv", sep=',')